FROM node:alpine

LABEL version="1.0"
LABEL description="Development image"

WORKDIR /app

COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]

RUN npm install -g nodemon

RUN npm install && npm cache clean --force

COPY . .

EXPOSE 5000

CMD ["npm","run", "dev"]